### PR TITLE
Overhaul Green's function factory functionality

### LINKED ISSUE #58: Replace Boost.MPL with Brigand
We need Boost.MPL for the fake run-time polymorphism in the Green's functions classes. Using C++11 this can be replaced by the much lighter Brigand library: https://github.com/edouarda/brigand

### PR DESCRIPTION
**Pull request by robertodr**
## Description
I am starting to remove some Boost dependencies from the code. I would like to only include what's strictly necessary from Boost, so that the transition to C++11 for version 2 (long awaited) can happen as smoothly as possible. When this PR is ready to go, we will only depend on:
- Boost.Odeint, because of the diffuse interfaces, but this will be phased out with #94 and/or other work from @ilfreddy 
- Boost.Any, because of Getkw. The discussion in #88 will provide the way forward for this.

### Changed
- Dispatching of Green’s functions in the factory is purely label-based. The input reader generates a string that holds the type of the Green’s function, the strategy for calculating its normal derivatives and the dielectric profile (if needed): `TYPE_DERIVATIVE_PROFILE`. The Green’s functions are subscribed to the factory using this label, which is then also the one used for their creation. Iteration over _lists of types_ to dispatch the correct template parameters is thus completely avoided. This removes the dependency on the metafunctions in `ForId.hpp` and the dependency on Boost.MPL, the Boost metaprogramming library.
- Dispatching of quadrature rules for the numerical boundary integral operator has been rewritten, removing the dependency on Boost.MPL.
- The input wrapping data `struct`-s have been modified to include the string defining the type of object and to remove now unused information.
- Formatting of output is done entirely using C++ streams, removing the dependency on Boost.Format.

### Removed
- Some unused files have been removed:
  * `Interpolation.hpp`
  * `Interpolation.cpp`
  * `Vector2.hpp`
  * `Vector3.hpp`
  * `ForId.hpp`
  * `DerivativeUtils.hpp`
- The `cavityType()`, `solverType()`, `greenInsideType()`, `greenOutsideType()`
  and `integratorType()` functions in the `Input` object have been removed.
  This information is now wrapped into the corresponding input-wrapping
  `struct`-s: `CavityData`, `SolverData`, `GreenData` and `BIOperatorData`.

## Todos
* **Developer Interest**
  - [x] Clean up input parsing from unused/unreleased functionality. Supersedes @ilfreddy's #81 
  - [x] Remove dependency on Boost.MPL. Close #58 (metaprogramming no longer needed)
  - [x] Remove dependency on Boost.Format.
  - [x] Provide range-based `for` loop implementation in places where `BOOST_FOREACH` is used. These are fenced with the `HAS_CXX11` preprocessor definition.
  - [x] Remove dependency on Boost.Variant
  - [x] Remove the GCC build on Mac OS X in favor of an Apple Clang build. GCC is not officially supported anyway (Thanks @calewis for pointing this out)
  ~- [ ] In view of #109, implement a Runge-Kutta 4th order ODE integrator to replace the one provided by Boost.Odeint. [This one](https://people.sc.fsu.edu/~jburkardt/cpp_src/rk4/rk4.html) should suffice for our purposes.~

## Status
~I would also like to tackle the use of Boost.Variant before marking it ready to go.~
- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
@arnfinn @ilfreddy can one of you try to compile this PR on Mac OS X with GCC (**not** Apple Clang)? I am getting a weird error message about a function in a system header not being defined...

**Comment by arnfinn** [comment]
I got the following error when I tried your branch with *MacPorts gcc5 5.5.0_0*, which I guess is the same as Travis get:
```
[  8%] Building CXX object src/cavity/CMakeFiles/cavity.dir/ICavity.cpp.o
In file included from /usr/include/unistd.h:638:0,
                 from /opt/local/include/zconf.h:475,
                 from /opt/local/include/zlib.h:34,
                 from /Volumes/repos/arnfinn/pcmsolver/src/utils/cnpy.hpp:17,
                 from /Volumes/repos/arnfinn/pcmsolver/src/utils/MathUtils.hpp:42,
                 from /Volumes/repos/arnfinn/pcmsolver/src/cavity/ICavity.cpp:32:
/usr/include/sys/select.h:114:19: error: 'fd_set' has not been declared
 int  pselect(int, fd_set * __restrict, fd_set * __restrict,
                   ^
/usr/include/sys/select.h:114:40: error: 'fd_set' has not been declared
 int  pselect(int, fd_set * __restrict, fd_set * __restrict,
                                        ^
/usr/include/sys/select.h:115:3: error: 'fd_set' has not been declared
   fd_set * __restrict, const struct timespec * __restrict,
   ^
make[2]: *** [src/cavity/CMakeFiles/cavity.dir/ICavity.cpp.o] Error 1
make[1]: *** [src/cavity/CMakeFiles/cavity.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by robertodr** [comment]
Thanks a lot @arnfinn. Yep, it's the same error. I have tried GCC 6.4.0 and GCC 7.2.0 on Travis, both installed with Homebrew. The fact that GCC 5.5.0 installed _via_ MacPorts gives the same error doesn't bode well. I guess when I pulled some Boost stuff out some `include`-s that were within the Boost headers were ripped away. Sadly ironic... I'll ask some of the local gurus here if they've ever seen this kind of problem. Can you run a `grep fd_set` in the `/usr/include/sys` directory?

**Comment by arnfinn** [comment]
```
$ grep fd_set /usr/include/sys/*.h
/usr/include/sys/_select.h:int	 select(int, fd_set * __restrict, fd_set * __restrict,
/usr/include/sys/_select.h:		fd_set * __restrict, struct timeval * __restrict)
/usr/include/sys/select.h: * [XSI] The <sys/select.h> header shall define the fd_set type as a structure.
/usr/include/sys/select.h:#include <sys/_types/_fd_setsize.h>
/usr/include/sys/select.h:#include <sys/_types/_fd_set.h>
/usr/include/sys/select.h:int	 pselect(int, fd_set * __restrict, fd_set * __restrict,
/usr/include/sys/select.h:		fd_set * __restrict, const struct timespec * __restrict,
/usr/include/sys/time.h: * [XSI] The fd_set type shall be defined as described in <sys/select.h>.
/usr/include/sys/time.h:#include <sys/_types/_fd_setsize.h>
/usr/include/sys/time.h:#include <sys/_types/_fd_set.h>
/usr/include/sys/types.h:#include <sys/_types/_fd_setsize.h>
/usr/include/sys/types.h:#include <sys/_types/_fd_set.h>
```

**Comment by robertodr** [comment]
Seems `struct fd_set` is really not there... Wonder where it went.

**Comment by arnfinn** [comment]
adding `#include <sys/select.h>` seems to help.

**Comment by robertodr** [comment]
Currently trying with Xcode 8gm. In which file did you include that system header?

**Comment by robertodr** [comment]
Newer Xcode didn't work either :/

**Comment by arnfinn** [comment]
In `ICavity.cpp`. Then the error moved to `Element.cpp`:)

**Pull request merged**
