### PR TITLE
CMake changes assoc. with Psi4 Superbuild

### PR DESCRIPTION
**Pull request by loriab**
Hi @robertodr , opening this PR to let you know what I'm doing and give you a chance to respond. It's not ready for merging. BTW, should I be doing this PR against a different branch?

This first commit pretty much imposes GNUInstallDirs so one can adjust install locations. Also, all the headers are moved behind a PCMSolver namespace (psi4's already been adjusted). Also, upon `make install`, some files were installing to `CMAKE_BINARY_DIR`, not `CMAKE_INSTALL_PREFIX`. I didn't understand that, so suppressed it. A few more notes along the way below.
- As far as I can tell, the GNUInstallDirs macro was added more than two years before cmake 2.8.12, so there shouldn't be any problems. If there are, can copy on in to cmake/ from github.
- I added a cmake/custom/export.cmake file and included it in top-level CMakeLists.txt . Since that says it's generated by autocmake, I figure you'll have to hook it up properly.
- According to https://cmake.org/cmake/help/v3.0/command/install.html, "install(PROGRAMS" is for executables that aren't targets. So I switched the signature to "install(TARGET run_pcm"
- libtaylor was installing internally to objdir, not externally to prefix
- switched (in Psi4) HAVE_PCMSOLVER to USING_PCMSolver. I'll switch back if HAVE_PCMSOLVER is a widespread thing.
- namespaced the headers
- At some point, I'm going to clear out `CLEAN_DIRECT_OUTPUT`. Justification [here](https://cmake.org/Wiki/CMake_FAQ) (though you'll have to search the page)

Current status wrt Psi4: If you build this branch and install it, then configure psi4 with
- build this pcmsolver branch and install it to `PFXE=/path/to/install-pcmsolver`
- configure Psi4 with 

```
 -DENABLE_PCMSolver=ON \
 -DPCMSOLVER_ROOT="${PFXE}/install-pcmsolver" \
 -DCMAKE_PREFIX_PATH="${PFXE}/install-libint-6-so;${PFXE}/install-pcmsolver" \
```
- then hardcode the staged driver into `psi4/share/psi4/python/pcm_placeholder.py` : `PCMSolver_PARSE_DIR = '/path/to/psi4/objdir/stage/${CMAKE_INSTALL_PREFIX}/external/pcmsolver/bin'
- then at runtime `export PYTHONPATH=/path/to/install-pcmsolver/bin:$PYTHONPATH`

### CODE REVIEW

**Comment by loriab** [comment]
I don't know what' up with the travis error below, btw. I tried a build with cmake 2.8.10, and it works just fine.
```
if given arguments:
    "NOT" "DEFINED" "OR" "" "STREQUAL" ""
```

**Comment by robertodr** [comment]
@loriab sorry for the late reply. I don't understand the Travis error either and will investigate. Also, the PR is fine against this branch. Everything looks good, but I need some more time to for a careful look.

**Comment by loriab** [comment]
No hurry at all, @robertodr, as PR is not ready for merge at this point. I just wanted to give you notice and notes as to what I'm working on.

**Comment by robertodr** [comment]
@loriab I am finally returning to this PR (sorry, but better late than never) I have made some extensive changes to the `master` branch on the private repository. These haven't yet been mirrored here on GitHub and the `release/1.Y` branch is not yet up to date with those. In order to minimize effort, I will import this PR to my current version of `master` and then sync with the GitHub mirror. I'll close the PR then and we can proceed from the updated `master`. What do you think?

**Comment by loriab** [comment]
Hi @robertodr, that sounds like a good plan. I haven't come back to PCMSolver lately in the great CMake-ing, so just let me know when and what is a good branch to work off of. Thanks!

**Comment by loriab** [comment]
Oh, and if it's easier to just transfer the edits by hand rather than doing a git operation to preserve history, feel free to do so.

**Comment by robertodr** [comment]
@loriab that is actually what I ended up doing. I am closing this PR. You should nuke your fork since I had to rewrite history. How do you suggest I proceed now? Should I look at the set up of CheMPS2 and/or Libint and bother you if there is something I don't understand?

**Comment by loriab** [comment]
Hi @robertodr, if you're willing to do some CMake revamping for PCMSolver, that'd be a great help. Ask me any questions, no matter how small.

* Yes, for the most part if you copy [libefp](https://github.com/psi4/libefp/tree/config3) for simple, [gdma](https://github.com/psi4/gdma) for Fortran, and [CheMPS2](https://github.com/SebWouters/CheMPS2) for complex and in particular simultaneous shared/static build, that'll be a good pattern. Basically, you want to get an exported target PCMSolverConfig.cmake being installed with the library, then read-in-able ultimately [here](https://github.com/psi4/psi4/blob/master/psi4/CMakeLists.txt#L60-L64).

* In psi4, the `PCMSOLVER_ROOT` will go away and be replaced by `CMAKE_PREFIX_PATH`. The `find_package(` will go from MODULE to Config (FindPCMSolver.cmake goes away). [This](https://github.com/psi4/psi4/blob/master/external/pcmsolver/CMakeLists.txt) it looks like I already started adapting. It should look a lot like the others (except GTFock) in the externals folder.

* One change in the new Psi4 superbuild is that instead of source (C++ from objdir, Py from source) and installed (C++ from install_prefix; Py from install_prefix), we now have inplace (C++ from objdir, Py from source), staged (C++ from objdir, Py from objdir), and installed (C++ from install_prefix; Py from install_prefix). The inplace is a special case that's handy for developing Py-side, but we don't demand that it be all-powerful. In fact, since pcm had to do `.in` and checked-in `.in` before, I'd say just arrange so that it runs from staged and don't try for inplace.

* The main trick is going to be all of pcm's dependencies since ideally, there's no local absolute paths in the Config*cmake files. But I think pcm pretty much builds its own dependencies, so we can make that as difficult (and proper cmake) or as simple (build them all and install alongside the pcm library) as we choose.

Basically, let me know any questions and how deeply you want to get involved in dependency flexibility. Thank goodness you've only Boost header libs.

* At one point, I thought pcm was actually building a python module, and I fished up the below. take anything that's useful.

```
>>> cat cmake/custom/python_sitepackages.cmake 
# extracted from FindPythonLibsNew

#STATIC
#n module extension
#   execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
#                        "import distutils.sysconfig, sys; sys.stdout.write(distutils.sysconfig.get_config_var('SO'))"
#                   OUTPUT_VARIABLE PYTHON_MODULE_EXTENSION
#                   RESULT_VARIABLE _PYTHON_MODULE_EXTENSION)
#
#   # Get Python site-packages directory
#   execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
#                        "import distutils.sysconfig, sys; sys.stdout.write(distutils.sysconfig.get_python_lib())"
#                    OUTPUT_VARIABLE PYTHON_SITE_PACKAGES
#                    OUTPUT_STRIP_TRAILING_WHITESPACE)



# According to http://stackoverflow.com/questions/646518/python-how-to-detect-debug-interpreter
# testing whether sys has the gettotalrefcount function is a reliable, cross-platform
# way to detect a CPython debug interpreter.
#
# The library suffix is from the config var LDVERSION sometimes, otherwise
# VERSION. VERSION will typically be like "2.7" on unix, and "27" on windows.
execute_process(COMMAND "${PYTHON_EXECUTABLE}" "-c"
    "from distutils import sysconfig as s;import sys;import struct;
print('.'.join(str(v) for v in sys.version_info));
print(sys.prefix);
print(s.get_python_inc(plat_specific=True));
print(s.get_python_lib(plat_specific=True));
print(s.get_config_var('SO'));
print(hasattr(sys, 'gettotalrefcount')+0);
print(struct.calcsize('@P'));
print(s.get_config_var('LDVERSION') or s.get_config_var('VERSION'));
"
    RESULT_VARIABLE _PYTHON_SUCCESS
    OUTPUT_VARIABLE _PYTHON_VALUES
    ERROR_VARIABLE _PYTHON_ERROR_VALUE
    OUTPUT_STRIP_TRAILING_WHITESPACE)

if(NOT _PYTHON_SUCCESS MATCHES 0)
    if(PythonLibsNew_FIND_REQUIRED)
        message(FATAL_ERROR
            "Python config failure:\n${_PYTHON_ERROR_VALUE}")
    endif()
    set(PYTHONLIBS_FOUND FALSE)
    return()
endif()

# Convert the process output into a list
string(REGEX REPLACE ";" "\\\\;" _PYTHON_VALUES ${_PYTHON_VALUES})
string(REGEX REPLACE "\n" ";" _PYTHON_VALUES ${_PYTHON_VALUES})
list(GET _PYTHON_VALUES 0 _PYTHON_VERSION_LIST)
list(GET _PYTHON_VALUES 1 PYTHON_PREFIX)
list(GET _PYTHON_VALUES 2 PYTHON_INCLUDE_DIR)
list(GET _PYTHON_VALUES 3 PYTHON_SITE_PACKAGES)
list(GET _PYTHON_VALUES 4 PYTHON_MODULE_EXTENSION)
list(GET _PYTHON_VALUES 5 PYTHON_IS_DEBUG)
list(GET _PYTHON_VALUES 6 PYTHON_SIZEOF_VOID_P)
list(GET _PYTHON_VALUES 7 PYTHON_LIBRARY_SUFFIX)

# Make sure the Python has the same pointer-size as the chosen compiler
# Skip if CMAKE_SIZEOF_VOID_P is not defined
if(CMAKE_SIZEOF_VOID_P AND (NOT "${PYTHON_SIZEOF_VOID_P}" STREQUAL "${CMAKE_SIZEOF_VOID_P}"))
    if(PythonLibsNew_FIND_REQUIRED)
        math(EXPR _PYTHON_BITS "${PYTHON_SIZEOF_VOID_P} * 8")
        math(EXPR _CMAKE_BITS "${CMAKE_SIZEOF_VOID_P} * 8")
        message(FATAL_ERROR
            "Python config failure: Python is ${_PYTHON_BITS}-bit, "
            "chosen compiler is  ${_CMAKE_BITS}-bit")
    endif()
    set(PYTHONLIBS_FOUND FALSE)
    return()
endif()

# The built-in FindPython didn't always give the version numbers
string(REGEX REPLACE "\\." ";" _PYTHON_VERSION_LIST ${_PYTHON_VERSION_LIST})
list(GET _PYTHON_VERSION_LIST 0 PYTHON_VERSION_MAJOR)
list(GET _PYTHON_VERSION_LIST 1 PYTHON_VERSION_MINOR)
list(GET _PYTHON_VERSION_LIST 2 PYTHON_VERSION_PATCH)

# Make sure all directory separators are '/'
string(REGEX REPLACE "\\\\" "/" PYTHON_PREFIX ${PYTHON_PREFIX})
string(REGEX REPLACE "\\\\" "/" PYTHON_INCLUDE_DIR ${PYTHON_INCLUDE_DIR})
string(REGEX REPLACE "\\\\" "/" PYTHON_SITE_PACKAGES ${PYTHON_SITE_PACKAGES})
```

**Comment by robertodr** [comment]
@loriab thanks for the detailed response! Could you open a new issue about this and copy-paste it there?

**Pull request closed without merging**
