### PR TITLE
help the reimport problem

### PR DESCRIPTION
**Pull request by loriab**
## Motivation and Context

If you run the parse file function twice with the same `import pcmsolver`, it gives a keyword already defined error with `getkw`. This causes trouble with psiapi and even worse with running a multiple pcm job with qcschema b/c the pcm input gets reparsed. @robertodr worked on this some. I may have opined that `reload` is never the answer. Nonetheless, the proposed changes do help. Has this already been tried and found troublesome?

## Todos

* **Developer Interest**

  - [ ] Feature1
* **User-Facing for Release Notes**

  - [ ] Feature2

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Questions

- [ ]  Question1

## Status

- [ ] Ready to go
- [ ] Cherry-pick to latest release branch

### CODE REVIEW

**Comment by loriab** [comment]
CI error is unrelated, I think:
```
  File "/home/travis/.local/lib/python3.5/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/travis/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 12, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/travis/.local/lib/python3.5/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/travis/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/home/travis/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 43, in <module>
    class PackageNotFoundError(ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
```

In local testing back on v1.2.1, I also get the following warnings, which you may well have already addressed in the meantime.
```
/home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:798
/home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:798
  /home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:798: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    collections.MutableMapping.register(ParseResults)

/home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:2389
/home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:2389
  /home/psilocaluser/toolchainconda/envs/py38/lib//python3.8/site-packages/pcmsolver/pyparsing.py:2389: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    elif isinstance(exprs, collections.Sequence):
```

**Comment by robertodr** [comment]
CI is in a sorry state. The changes look good, I'll switch to GitHub actions to get meaningful feedback from CI again. The warnings look familiar: I have accumulated patches here and there, but never merged them :'(

**Comment by loriab** [comment]
> CI is in a sorry state. The changes look good, I'll switch to GitHub actions to get meaningful feedback from CI again. The warnings look familiar: I have accumulated patches here and there, but never merged them :'(

np, I have limping Travis-CI repos, too. I'm thinking pb11 is a good model for all arch + compiled + GHA CI, if it isn't already on your radar.

**Comment by robertodr** [comment]
I have this template: https://github.com/MRChemSoft/mrchem/blob/master/.github/workflows/build-test.yml

**Review by robertodr — APPROVED** [review]
Thanks!

**Comment by robertodr** [comment]
I need to synchronize some changes in the Fortran interface before making a new release.

**Pull request merged**
