### PR TITLE
mods for export cmake target

### PR DESCRIPTION
**Pull request by loriab**
* Added a PCMSolverConfig to export `PCMSolver::pcm` target
* Added a `SHARED_LIBRARY_ONLY` counterpart to `STATIC_LIBRARY_ONLY`
* Optionally install the python into lib/site-pack/pcmsolver/ instead of bin/ . I'd rather have a `__init__.py` within, but I think that'd mean relative imports to codata, getkw, etc.

### CODE REVIEW

**Comment by loriab** [comment]
Ok, those immediate comments should be taken care of. Feel free to squash merge this in the end, by the way.

**Comment by loriab** [comment]
As I remember, you have to support an ancient CMake. I expect you have a copy of that version and so can test where some if-cmake-version blocks need to go. [This](https://github.com/pybind/pybind11/blob/master/CMakeLists.txt#L129-L135) is one guide, but that project has a min version of 2.8.12, so there may be more. Everything I've done is legit by 3.0.

**Comment by loriab** [comment]
That last commit gets me to only the 3 standalone tests failing with some path problem:
```
Traceback (most recent call last):
  File "/theoryfs2/ds/cdsgroup/psi4-compile/externals/pcmsolver2/objdir7/mylib/python2.7/site-packages/pcmsolver/pcmsolver.py", line 751, in <module>
    main()
  File "/theoryfs2/ds/cdsgroup/psi4-compile/externals/pcmsolver2/objdir7/mylib/python2.7/site-packages/pcmsolver/pcmsolver.py", line 158, in main
    execute(parsed)
  File "/theoryfs2/ds/cdsgroup/psi4-compile/externals/pcmsolver2/objdir7/mylib/python2.7/site-packages/pcmsolver/pcmsolver.py", line 200, in execute
    subprocess.check_output([executable, parsedFile])
  File "/theoryfs2/ds/cdsgroup/miniconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/theoryfs2/ds/cdsgroup/miniconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/theoryfs2/ds/cdsgroup/miniconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

However, besides that, there's a lot of `No tests ran` messages that you may want to investigate.

**Comment by robertodr** [comment]
@loriab thanks for your great work on this!

**Pull request merged**
