### PR TITLE
Introduce pcmsolver/__init__.py

### PR DESCRIPTION
**Pull request by bast**
Introduce `pcmsolver/__init__.py` and move python scripts below `bin/pcmsolver/` to limit the scope of its imports.

## What is not part of this PR

I have not changed the `tmp-pcmsolver-py` behavior. I think that the configure and *.in files pattern is overused in this project (and many other projects) and I would rather recommend to use scripts which do not inherit configuration state. This would also remote the need to create the temporary file. But I think this is outside this issue.

Also I recommend to separate the library part from the launcher part in `pcmsolver.py`. This was not done in this change.

## Motivation and Context

See #40.

## How Has This Been Tested?

Running `ctest` locally and comparing with pristine clone.

## Questions

- [x]  Python package currently only exports `parse_pcm_input` - should it export more functions?

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
Thanks! I agree with your assessment of the situation. Can you open issues so that we don't forget? Concerning functions to be exported, `parse_pcm_input` is the only thing to export. The rest is internal and, as you said, should be in a library not in the main script. Can you address the comments from @MinazoBot ?

**Comment by bast** [comment]
Documented in changelog. I quickly grepped through `doc/` but my feeling is that this change does not affect anything documented. If I missed something, can you please point me to the documentation section which should be adapted or extended?

**Comment by bast** [comment]
Forgot to mention that I have tested the import and parsing an example input file as described by @loriab. We could consider adding an automated test for that import if you think this is worthwhile.

**Comment by bast** [comment]
The mentioned follow-up issues are tracked in #111 and #112.

**Comment by robertodr** [comment]
@bast the last two comments from @MinazoBot we can ignore :smile: Thanks for your help on this!

**Comment by loriab** [comment]
Do you think you could use entry points, so the code always stays in the module (under `lib/`) and never gets installed to `bin/` while entry points provide the command-line access? Could unify the install.

(I've only experimented with entry points, never found a clear use for them. Probably not the best but definitely an amusing blog post: http://amir.rachum.com/blog/2017/07/28/python-entry-points/)

**Comment by bast** [comment]
Interesting! I did not know about entry points until today. Until now I was programming them "manually". Just to be clear: the work on the Python interface did not stop here. The question is: what is our ambition to do in this pull request? I would definitely like a better separation between bin and lib. I personally like smaller issues and smaller PRs but no problem to keep this one open and do all the work here.

**Comment by loriab** [comment]
I only heard about entry points b/c I saw a conda build keyword for them. Then it struck me today that they may be a way around the `PYMOD_INSTALL_FULLDIR` complexity and a way to make the two (py mod and command-line) use cases available w/o toggling the install. And alternate installs [make packagers unhappy](https://github.com/ilyak/libefp/issues/11).

My overarching goal with this PR is to tuck pcmsolver install files away behnd a namespace where they can't cause conflicts. A python module is a common form; namespaced bin is less so, as far as I've seen. Entry points seemed a way of connecting the two. Any of the above get my vote.

**Comment by bast** [comment]
I agree with your motivations. Let's think about it for a moment. I need to experiment a bit with entry points to get better feel.

**Pull request merged**
