### PR TITLE
Restore compilation for g++ < v5.1

### PR DESCRIPTION
**Pull request by bast**
## Description

The troublesome compiler flags are only included if version is 5.1 or above.

## Motivation and Context

https://github.com/PCMSolver/pcmsolver/issues/76

## How Has This Been Tested?

Tested locally.

## Todos

* **User-Facing for Release Notes**

  - [x] Compilation restored for g++ < v5.1.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Status

- [ ]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
I restarted one CI job. One of the tests crashed, I think.

**Comment by arnfinn** [comment]
Should you update the changelog, or is it not relevant for such fixes?

**Comment by bast** [comment]
Good point. I think it is relevant. I will add it there.

**Comment by arnfinn** [comment]
You can copy and paste it from the fixed section under Version 1.1.8:)

**Comment by robertodr** [comment]
@bast is this ready to go? Or do you plan to update the changelog?

**Comment by bast** [comment]
Sorry, this got lost in my email pile - yes I will update the changelog.

**Comment by bast** [comment]
It's now in the changelog - once Travis et al. are happy, it is ready to go from my perspective.

**Comment by bast** [comment]
The tests used to pass IIRC, now they failed after I modified changelog.

**Comment by robertodr** [comment]
It's Mac OS X on Travis acting up. Either I bypass checks and merge this one or you can try to fix Travis. Up to you.

**Pull request merged**
