### PR TITLE
[doc] mv doc out of cmake; add matplotlib to doc/requirements.txt

### PR DESCRIPTION
**Pull request by arnfinn**
Matplotlib is needed for building the documentation (locally).

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
Thanks for catching this one! I think the `requirements.txt` should actually be in the top-level directory not in `doc`. In this way people using virtual environments get all Python dependencies. 
Could you:
1. Look over the file `doc/programmers/documentation.rst` to make sure that all dependencies are listed? Also throw in there that there's a `requirements.txt` to install the Python dependencies.
2. Test with a virtual environment. So that we make sure once and for all that we have all Python dependencies declared in one place.

**Comment by arnfinn** [comment]
Should we also add these packages to `cmake/custom/documentation.cmake` or should we make it possible to make the doc target even if the python packages are missing? I am in favour of the latter, because then you do not have to rerun setup if you forgot a package. Maybe spit out an understandable error message if you run `make doc` without the required packages installed?

**Comment by bast** [comment]
My personal opinion is that documentation should possibly be decoupled from the configuration and build framework. I have done it differently in the past. Of course it is convenient to type `make doc`. But it is not too much more difficult to type `sphinx-build doc/ _build/`.

**Comment by robertodr** [comment]
Well, the best option is to reduce the dependencies :smile: `conf.py` can do what CMake does, since when running on ReadTheDocs there is no CMake. At the moment, the only thing that the CMake layer provides  is checking dependencies. If we change the docs to say what should be installed, how, how to build and let `conf.py` spit out errors, we can remove the `make doc` target.

**Comment by bast** [comment]
The advantage of decoupling this is that you can still build docs even though the compilation might be broken. We had this situation in the past in another project.

**Comment by arnfinn** [comment]
I would also prefer removing this from cmake. Remove a layer, a layer that just makes it more difficult for newcomers.

**Comment by robertodr** [comment]
@arnfinn Go for it! :smile:

**Comment by arnfinn** [comment]
@robertodr I will try :)

**Comment by arnfinn** [comment]
Should I skip this pull request and integrate it into pull request #102 instead?

**Comment by arnfinn** [comment]
Moved to pull request #102

**Pull request closed without merging**
