### PR TITLE
Fix API for the surface function NumPy save/load functions

### LINKED ISSUE #70: Add tests for surface functions saving/loading API functions
API functions for saving/loading surface functions are currently barely tested, if at all. This is very critical to check that string passing from Fortran is not broken.

### PR DESCRIPTION
**Pull request by robertodr**
This PR fixes the Fortran API for the surface function NumPy save/load functions and adds calls to these functions in the C and Fortran host example executables.
These calls are just to exercise these functions and protect against "basic" API breakages, thus fixing #70 
A bug (dormant) was also fixed in the C++ API: the save function was writing the NumPy array file with the incorrect dimension information, subsequently causing the load function to crash.

## Todos

* **Developer Interest**

  - [x] Fix Fortran API
  - [x] Fix C++ API

## Types of changes

- [x] Bug fix #70 

## Status

- [x]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
@arnfinn @ilfreddy @bast Can we get this merged?

**Comment by bast** [comment]
You don't mind the merge commits there? If not, then I can press the green button.

**Comment by robertodr** [comment]
@bast please squash the merge commits. Thanks!

**Comment by bast** [comment]
You mean all 4 commits into 1 (this is easy) - or commits 3 and 4 into 2? The latter would require me to file a PR to you fixing this which would update this PR.

**Comment by robertodr** [comment]
I would save only the first two commits. Are you sure you can't squash at
will with the web UI?

Il sab 24 giu 2017, 17:44 Radovan Bast <notifications@github.com> ha
scritto:

**Comment by bast** [comment]
There is a button that says that 4 commits will be squashed into one. I am not sure there is more fine-grain after that button. Doubt it but of course I will be glad to be proven wrong.

**Comment by robertodr** [comment]
I rebased wrt `release/1.Y`, I recommend merge without squashing.

**Comment by bast** [comment]
Thanks!

**Pull request merged**
