### PR TITLE
[WIP] Use Runge-Kutta-Fehlberg 7(8) integrator in SphericalDiffuse

### PR DESCRIPTION
**Pull request by robertodr**
This PR aims at replacing the [Bulirsch-Stoer](https://en.wikipedia.org/wiki/Bulirsch%E2%80%93Stoer_algorithm) adaptive integrator with the non-adaptive [Runge-Kutta-Fehlberg 7(8)](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta%E2%80%93Fehlberg_method) in the calculation of the radial part of the spherical diffuse Green's function.
See also [here](http://sirrah.troja.mff.cuni.cz/yarko-site/tmp/dt/mptest.html)

## Motivation and Context
The non-adaptive integrator affords faster solution of the radial differential equation, thus allowing the use of more spherical harmonics in the expansion of the radial part.
The issues I noticed in the initial implementation, _i.e._ that non-adaptive integrators were not robust enough with respect to small widths of the interface, was due to a buggy implementation of the `splineInterpolation` function. This has now been fixed, based on work we did with @ilfreddy.

## Todos
* **Developer Interest**
  - [x] Fix possible bug in `splineInterpolation`.
  - [x] Switch from Bulirsch-Stoer to Runge-Kutta-Fehlberg 7(8).
  - [ ] Adjust reference values in the `green_spherical_diffuse` test

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Questions
- @ilfreddy check if this makes any difference on run time for your test cases.

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by robertodr** [comment]
Seems to work fine so far (Travis complains because of some Boost headers) I think I'll bring this one a step further and introduce a simpler implementation of RKF-78 and the Legendre polynomials. We can then expunge Boost.Math.

**Comment by bast** [comment]
Nice!

**Comment by ilfreddy** [comment]
I think this is now obsolete because #109 is a branch which originally started from this one.

**Comment by robertodr** [comment]
Superseded by #109. Closing.

**Pull request closed without merging**
